theme: minima

title: Karen Piech

github-username: klpiech

# author:
    #name: GitHub user klpiech
  
#minima:
  #social_links:
   # - { platform: github,  user_url: "https://github.com/klpiech" }
    #- { platform: linkedin, user_url: "https://www.linkedin.com/in/karen-piech-03034a7" }
